export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categroy/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS:
    "categroy/FETCH_CATEGORIES_FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAIL: "categroy/FETCH_CATEGORIES_FAIL",
};
